---
#
# Instaling and configuring MetricBeat
#

- name: Install metricbeat
  yum:
    name: metricbeat
    state: present

- name: Find password for elastic user
  shell: cat /tmp/elkpassword.txt | grep elastic | awk '{print $4}' | tail -1
  register: elasticpass

- name: Configure connection
  blockinfile:
    path: /etc/metricbeat/metricbeat.yml
    insertafter: "output.elasticsearch:"
    block: |
          hosts: ["http://localhost:9200"]
          username: "elastic"
          password: ""{{ elasticpass.stdout }}""
          setup.kibana:
          host: "http://localhost:5601"


- name: Enable modules vsphere
  shell: metricbeat modules enable vsphere

- name: Metricbeat setup
  shell: metricbeat setup

- name: Starting metricbeat
  service: 
     name: metricbeat
     state: started
     enabled: yes
